apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sariel
  namespace: angel-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-sariel
  template:
    metadata:
      labels:
        app: redis-sariel
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: '50m'
              memory: '64Mi'
            limits:
              cpu: '200m'
              memory: '256Mi'
